services:
  - type: web
    name: backend-ai-code-review
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ALLOW_ORIGINS
        value: https://frontend-ai-powered-code-review-pjhn84buv-revems-projects.vercel.app
      - key: GEMINI_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false

databases:
  - name: mongodb
    plan: free
